# Generated by Django 3.2.16 on 2022-12-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('course', models.CharField(max_length=64)),
            ],
        ),
    ]
